language: cpp

before_script:
  - export CODECOV_TOKEN=5cfca0f2-2ece-4a2e-9f02-5fe479e96813

script:
  - /Users/travis/build/nyanzebra/cat/script.sh

before_install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"
  - echo "$TRAVIS_OS_NAME"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      /Users/travis/build/nyanzebra/cat/osx_install.sh
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      /Users/travis/build/nyanzebra/cat/linux_install.sh
    fi

#https://github.com/Microsoft/GSL/blob/master/.travis.yml
install:
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  # - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  # - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"
  - cmake --version
  - cd "${TRAVIS_BUILD_DIR}"

matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      sudo: required
    - os: osx

compiler:
  - clang++
  - g++

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
