version: 2.0
jobs:
  build_gcc_latest:
    branches:
      only:
        - master
        - develop
        - feature/*
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: export CODECOV_TOKEN=5cfca0f2-2ece-4a2e-9f02-5fe479e96813; linux_install.sh; script.sh;
    test:
      post:
        - bash <(curl -s https://codecov.io/bash)
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build_gcc_latest
